/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-25 15:27:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class asignacion_002dequipos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <!-- Favicon -->\r\n");
      out.write("        <link href=\"images/favicon.ico\" rel=\"icon\">\r\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <!-- Bootstrap css -->\r\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        <!-- Main css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("            integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("            crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("        <!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("        <title>Asignacion de equipos | Toulouse Lautrec</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--Navbar-->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("        <!--//Navbar-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid background\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h1 class=\"pt-5 text-center\">Asignación de Equipos</h1>\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center align-items-center text-white\">\r\n");
      out.write("                    <form class=\"w-75\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"employeeName\">Nombre del Colaborador</label>\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"basic-addon1\">\r\n");
      out.write("                              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\"\r\n");
      out.write("                                viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                  d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\">\r\n");
      out.write("                                </path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"employeeName\" placeholder=\"Nombre del colaborador\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"employeeDepartment\">Departamento</label>\r\n");
      out.write("                          <select class=\"form-select\" id=\"employeeDepartment\">\r\n");
      out.write("                            <option selected>Seleccione un departamento</option>\r\n");
      out.write("                            <option>TI</option>\r\n");
      out.write("                            <option>Comunicación</option>\r\n");
      out.write("                            <option>Marketing</option>\r\n");
      out.write("                            <option>Administración</option>\r\n");
      out.write("                            <option>Recursos Humanos</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"equipmentName\">Nombre del Equipo</label>\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"basic-addon1\">\r\n");
      out.write("                              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\"\r\n");
      out.write("                                viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                  d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\">\r\n");
      out.write("                                </path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"equipmentName\" placeholder=\"Nombre del equipo\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"equipmentType\">Tipo de Equipo</label>\r\n");
      out.write("                          <select class=\"form-select\" id=\"equipmentType\">\r\n");
      out.write("                            <option selected>Seleccione un tipo de equipo</option>\r\n");
      out.write("                            <option>Computadora</option>\r\n");
      out.write("                            <option>Dispositivo Móvil</option>\r\n");
      out.write("                            <option>Periférico</option>\r\n");
      out.write("                          </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"serialNumber\">Número de Serie</label>\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                            <span class=\"input-group-text\" id=\"basic-addon1\">\r\n");
      out.write("                              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\"\r\n");
      out.write("                                viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                  d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0\">\r\n");
      out.write("                                </path>\r\n");
      out.write("                              </svg>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"serialNumber\" placeholder=\"Número de serie del equipo\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                          <label for=\"assignmentDate\">Fecha de Asignación</label>\r\n");
      out.write("                          <input type=\"date\" class=\"form-control\" id=\"assignmentDate\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                          <label for=\"additionalNotes\">Notas Adicionales</label>\r\n");
      out.write("                          <textarea class=\"form-control\" id=\"additionalNotes\" placeholder=\"Agregar notas adicionales\"\r\n");
      out.write("                            rows=\"3\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary mt-3 mb-5\">Asignar Equipo</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- for bootstrap working -->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"\r\n");
      out.write("            integrity=\"sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"libs/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <!-- //for bootstrap working -->\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
