/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-25 16:39:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class incidentes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"images/favicon.ico\" rel=\"icon\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"css/bootstrap.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      media=\"all\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- Bootstrap css -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("    <!-- Main css -->\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("      integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("      referrerpolicy=\"no-referrer\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- Font-Awesome-Icons-CSS -->\r\n");
      out.write("    <title>Registro de incidente | Toulouse Lautrec</title>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <!--Navbar-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "components/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <!--//Navbar-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid background\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"text-end\">\r\n");
      out.write("          <button\r\n");
      out.write("            type=\"submit\"\r\n");
      out.write("            class=\"btn btn-primary mt-3\"\r\n");
      out.write("            name=\"action\"\r\n");
      out.write("            value=\"incidentes\"\r\n");
      out.write("            onclick=\"window.location.href='lista-incidentes.jsp'\"\r\n");
      out.write("          >\r\n");
      out.write("            Lista de Incidentes\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h1 class=\"mt-5 text-center\">Registro de Incidente</h1>\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"col-12 d-flex justify-content-center align-items-center text-white\"\r\n");
      out.write("        >\r\n");
      out.write("          <form class=\"w-75\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <label for=\"userName\">Nombre del usuario</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"userName\"\r\n");
      out.write("                  placeholder=\"Nombre del usuario\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"userArea\">Área que pertenece</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"userArea\"\r\n");
      out.write("                  placeholder=\"Área (ej: Marketing)\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"category\">Categoría</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"category\">\r\n");
      out.write("                  <option selected>Seleccione una categoria</option>\r\n");
      out.write("                  <option>Hardware</option>\r\n");
      out.write("                  <option>Software</option>\r\n");
      out.write("                  <option>Red</option>\r\n");
      out.write("                  <option>Otros</option>\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"subcategory\">Subcategoría</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"subcategory\">\r\n");
      out.write("                  <option selected>Seleccione una subcategoria</option>\r\n");
      out.write("                  <option>Problema de Hardware</option>\r\n");
      out.write("                  <option>Falla de Software</option>\r\n");
      out.write("                  <option>Problema de Red</option>\r\n");
      out.write("                  <option>Otro</option>\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"createDate\">Fecha de Creacion</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"date\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"createDate\"\r\n");
      out.write("                  placeholder=\"Fecha de Creacion\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"closeDate\">Fecha de Cierre</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"date\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"closeDate\"\r\n");
      out.write("                  placeholder=\"Fecha de Cierre\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"source\">Tipo de Contacto</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"source\">\r\n");
      out.write("                  <option selected>Seleccione un tipo de contacto</option>\r\n");
      out.write("                  <option>Teléfono</option>\r\n");
      out.write("                  <option>Correo</option>\r\n");
      out.write("                  <option>In situ</option>\r\n");
      out.write("                  <option>Chat</option>\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"userEmail\">Correo electrónico</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"email\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"userEmail\"\r\n");
      out.write("                  placeholder=\"Correo electrónico\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"equipmentLocation\">Ubicación del equipo</label>\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"equipmentLocation\"\r\n");
      out.write("                  placeholder=\"Ubicación del equipo\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-6\">\r\n");
      out.write("                <label for=\"status\">Estado</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"status\" onchange=\"toggleWaitReason()\">\r\n");
      out.write("                  <option selected>Seleccione un Estado</option>\r\n");
      out.write("                  <option>Abierto</option>\r\n");
      out.write("                  <option>Pendiente</option>\r\n");
      out.write("                  <option>Cancelado</option>\r\n");
      out.write("                  <option>Resuelto</option>\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("             <div class=\"form-group col-md-6\" id=\"sourceContainer\" style=\"display:none;\">\r\n");
      out.write("               <label for=\"source\">Motivo de espera</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"source\">\r\n");
      out.write("                  <option selected>Seleccione un motivo de espera</option>\r\n");
      out.write("                  <option>En espera de proveedor</option>\r\n");
      out.write("                  <option>En espera de atención</option>\r\n");
      out.write("                  <option>En espera de usuario</option>\r\n");
      out.write("                </select>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("              <div class=\"form-group col-md-12\">\r\n");
      out.write("                <label for=\"problemDescription\">Descripción del problema</label>\r\n");
      out.write("                <textarea\r\n");
      out.write("                  class=\"form-control\"\r\n");
      out.write("                  id=\"problemDescription\"\r\n");
      out.write("                  placeholder=\"Describa el problema\"\r\n");
      out.write("                  rows=\"3\"\r\n");
      out.write("                ></textarea>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group col-md-12\" style=\"margin-top: 15px\">\r\n");
      out.write("                <label for=\"attachment\">Adjuntar archivos (Opcional)</label>\r\n");
      out.write("                <input type=\"file\" class=\"form-control-file\" id=\"attachment\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button\r\n");
      out.write("              type=\"submit\"\r\n");
      out.write("              style=\"margin-top: 15px\"\r\n");
      out.write("              class=\"btn btn-primary mb-4\"\r\n");
      out.write("            >\r\n");
      out.write("              Enviar Incidente\r\n");
      out.write("            </button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- for bootstrap working -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script src=\"libs/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- //for bootstrap working -->\r\n");
      out.write("\r\n");
      out.write("     <script>\r\n");
      out.write("          function toggleWaitReason() {\r\n");
      out.write("            var status = document.getElementById('status').value;\r\n");
      out.write("            var sourceContainer = document.getElementById('sourceContainer');\r\n");
      out.write("            if (status === 'Pendiente') {\r\n");
      out.write("              sourceContainer.style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("              sourceContainer.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
